### ISSUE TITLE
Unrecognized function or variable 'doplot'.

### ISSUE THREAD

**Issue by mok33** [gioelecrispo/wor#1]
Hi I have error : Unrecognized function or variable 'doplot'. when I Try to run the example from readme.

`:~/XPmatlab/wor/src$ matlab
MATLAB is selecting SOFTWARE OPENGL rendering.

                                        < M A T L A B (R) >
                              Copyright 1984-2022 The MathWorks, Inc.
                              R2022a (9.12.0.1884302) 64-bit (glnxa64)
                                         February 16, 2022

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
>> clearvars -except thresholds weights
>> restoredefaultpath
>> addpath(genpath('./'))
>> imagepath = '../databases/examples/high/c-092-02__thin.png';
>> [x, y, wor_result] = wor(imagepath, doplot)
Unrecognized function or variable 'doplot'.`

**Comment by mok33** [comment]
Hi, I understand that my issue is invalid. Can you please tell how to run the function wor() ?

**Comment by gioelecrispo** [comment]
Hi @mok33 ! Thank you for using the software!
As you probably understand, doplot is an optional input of the wor function. It could be equal to 0 if you don't want to plot wor results, 1 otherwise. However, for some reasons, some files were not pushed; I fixed it and I updated the README.md, pointing out that doplot is an optional flag.
Hope you find everything good and interesting.
